export type Category =
  | "Trauma"
  | "Cardiac"
  | "Lung"
  | "OB"
  | "Abdominal"
  | "Vascular"
  | "Neuro"
  | "Procedural";

export interface Protocol {
  id: string;
  name: string;
  shortName: string;
  category: Category;
  indication: string;
  views: string[];
  keyFindings: string[];
  commonPitfalls: string[];
  tip: string;
  icon: string;
  difficulty: "Basic" | "Intermediate" | "Advanced";
  estimatedTime: string;
  aiMeasurements: string[];
  anomaliesDetected: string[];
}

export const PROTOCOLS: Protocol[] = [
  {
    id: "efast",
    name: "eFAST — Extended FAST",
    shortName: "eFAST",
    category: "Trauma",
    indication: "Blunt/penetrating trauma; hemodynamic instability; free fluid assessment",
    views: ["RUQ (Morison's Pouch)", "LUQ (Splenorenal)", "Pelvis (Retrovesical/Retrouterine)", "Subxiphoid Cardiac", "Bilateral Lung (×2)"],
    keyFindings: ["Free fluid (anechoic stripe)", "Pericardial effusion", "Lung sliding (PTX)", "Hemopneumothorax"],
    commonPitfalls: ["Perinephric fat vs. fluid", "Collapsed IVC vs. fluid", "Suboptimal subxiphoid window"],
    tip: "Always start with RUQ — highest yield in trauma. Compare both flanks symmetrically.",
    icon: "🔴",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Free fluid depth (mm)", "Pericardial effusion size"],
    anomaliesDetected: ["Free fluid", "Pericardial effusion", "Pneumothorax", "Hemothorax"],
  },
  {
    id: "cardiac-plax",
    name: "Cardiac: Parasternal Long Axis",
    shortName: "PLAX",
    category: "Cardiac",
    indication: "Cardiac function assessment; effusion; valve pathology",
    views: ["Parasternal Long Axis (PLAX)"],
    keyFindings: ["LV systolic function", "Pericardial effusion", "Aortic root dilation", "MV pathology", "EPSS"],
    commonPitfalls: ["Mistaking epicardial fat for effusion", "Off-axis view overestimates chamber size"],
    tip: "Probe at 3rd–4th ICS, left sternal border. Rotate counterclockwise to align with cardiac axis.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["EPSS (mm)", "LV internal dimension", "LA diameter", "Aortic root diameter"],
    anomaliesDetected: ["Pericardial effusion", "Reduced EF (EPSS >1cm)", "Aortic dilation", "Posterior effusion"],
  },
  {
    id: "cardiac-psax",
    name: "Cardiac: Parasternal Short Axis",
    shortName: "PSAX",
    category: "Cardiac",
    indication: "Wall motion assessment; RV pressure; LV geometry",
    views: ["PSAX — Mitral valve level", "PSAX — Papillary muscle level", "PSAX — Apical level"],
    keyFindings: ["Regional wall motion abnormality", "D-sign (RV strain)", "LV geometry (donut shape)"],
    commonPitfalls: ["True short axis requires circular LV — if elliptical, adjust rotation"],
    tip: "From PLAX, rotate probe 90° clockwise. Mitral valve level shows 'fish mouth' appearance.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Fractional shortening", "D-sign severity"],
    anomaliesDetected: ["Wall motion abnormality", "RV strain (D-sign)", "Pericardial effusion"],
  },
  {
    id: "cardiac-a4c",
    name: "Cardiac: Apical 4-Chamber",
    shortName: "A4C",
    category: "Cardiac",
    indication: "EF estimation; chamber sizing; valve assessment",
    views: ["Apical 4-Chamber (A4C)"],
    keyFindings: ["All 4 chambers", "MV and TV function", "Apical wall motion", "EF (visual/biplane)"],
    commonPitfalls: ["Foreshortened apex gives falsely elevated EF", "Patient positioning critical (left lateral decubitus)"],
    tip: "Position patient in left lateral decubitus. Probe at cardiac apex, marker toward left shoulder.",
    icon: "❤️",
    difficulty: "Advanced",
    estimatedTime: "3–4 min",
    aiMeasurements: ["LV EF estimate (%)", "LA volume index", "E/A ratio estimate"],
    anomaliesDetected: ["Reduced EF", "RV dilation", "Apical wall motion abnormality", "Mitral regurgitation signs"],
  },
  {
    id: "ivc",
    name: "IVC Collapsibility (Fluid Status)",
    shortName: "IVC",
    category: "Cardiac",
    indication: "Volume status assessment; fluid responsiveness; CVP estimation",
    views: ["Subxiphoid IVC (longitudinal)", "M-mode through IVC at 2cm from junction"],
    keyFindings: ["IVC diameter (max)", "Collapsibility with respiration", "Respiratory variation"],
    commonPitfalls: ["IVC vs. aorta confusion", "Spontaneous breathing vs. ventilated patients — opposite interpretation"],
    tip: "Measure IVC 2cm from IVC-RA junction. Collapsibility >50% = likely volume responsive (spontaneous breathing).",
    icon: "❤️",
    difficulty: "Basic",
    estimatedTime: "2 min",
    aiMeasurements: ["IVC max diameter (cm)", "IVC min diameter (cm)", "Collapsibility Index (%)"],
    anomaliesDetected: ["Dilated IVC (>2.1cm)", "Plethoric IVC", "Flat IVC (<0.9cm)"],
  },
  {
    id: "lung-blue",
    name: "Lung: BLUE Protocol",
    shortName: "BLUE Protocol",
    category: "Lung",
    indication: "Dyspnea; respiratory failure; pneumonia vs. CHF vs. PE vs. PTX differentiation",
    views: ["Upper BLUE Point (bilateral)", "Lower BLUE Point (bilateral)", "PLAPS Point (bilateral)"],
    keyFindings: ["A-lines (air, normal/PTX)", "B-lines (fluid, interstitial)", "Lung sliding", "Pleural effusion", "Lung consolidation"],
    commonPitfalls: ["3+ B-lines per zone required to be significant", "Z-lines vs. B-lines (Z-lines don't reach far field)"],
    tip: "Use high-frequency linear probe for pleural line detail. Low-frequency for deeper pathology.",
    icon: "🫁",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["B-line count per zone", "Pleural effusion depth (mm)"],
    anomaliesDetected: ["B-lines (≥3/zone)", "Absent lung sliding", "Consolidation", "Pleural effusion"],
  },
  {
    id: "lung-effusion",
    name: "Lung: Pleural Effusion",
    shortName: "Pleural Effusion",
    category: "Lung",
    indication: "Pleural effusion detection and quantification; thoracentesis guidance",
    views: ["Posterior-lateral chest (sitting or lateral decubitus)", "Diaphragm visualization"],
    keyFindings: ["Anechoic vs. complex effusion", "Diaphragm descent", "Compressive atelectasis", "Fibrinous septations"],
    commonPitfalls: ["Confusing ascites with pleural effusion — find diaphragm landmark"],
    tip: "Spine sign: if vertebrae visible below diaphragm on left side, effusion present.",
    icon: "🫁",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Effusion depth (cm)", "Estimated volume (mL)"],
    anomaliesDetected: ["Simple effusion", "Complex/exudative effusion", "Septated effusion"],
  },
  {
    id: "ob-first-trimester",
    name: "OB: First Trimester Dating",
    shortName: "OB 1st Tri",
    category: "OB",
    indication: "Gestational age confirmation; viable IUP; ectopic exclusion",
    views: ["Longitudinal uterus (GS)", "Embryo with CRL measurement", "Adnexa bilateral", "Cervix"],
    keyFindings: ["Gestational sac", "Yolk sac", "Embryo (CRL)", "Fetal cardiac motion", "Adnexal masses"],
    commonPitfalls: ["Pseudogestational sac (ectopic) vs. true GS — look for double decidual sign", "Empty sac — may be too early (<5.5 weeks)"],
    tip: "Transabdominal first, then transvaginal if unclear. CRL measurement: straight line crown to rump, neutral position.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "5–10 min",
    aiMeasurements: ["CRL (mm)", "Gestational Age (weeks+days)", "EDD", "GS mean diameter (mm)"],
    anomaliesDetected: ["Subchorionic hematoma", "Irregular GS", "No cardiac motion (>6 weeks CRL)", "Adnexal mass", "Free fluid (ectopic risk)"],
  },
  {
    id: "ob-second-trimester",
    name: "OB: Second Trimester Biometry",
    shortName: "OB 2nd Tri",
    category: "OB",
    indication: "Gestational age; fetal growth; EFW; anatomy survey",
    views: ["BPD/HC plane (transthalamic)", "AC plane (stomach/UV junction)", "Femur length", "Placental location"],
    keyFindings: ["Fetal biometry parameters", "EFW percentile", "AFI/deepest pocket", "Placental position"],
    commonPitfalls: ["BPD: must visualize cavum septi pellucidi and thalami", "AC: true transverse at liver/umbilical vein junction"],
    tip: "Standard growth curves: Hadlock 1984 for EFW; Hadlock 1982 for individual parameters.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "10–15 min",
    aiMeasurements: ["BPD (mm)", "HC (mm)", "AC (mm)", "FL (mm)", "EFW (g)", "GA by biometry", "EFW percentile"],
    anomaliesDetected: ["IUGR pattern (AC lag)", "Macrosomia", "FL/AC discordance", "Placenta previa signs"],
  },
  {
    id: "aaa",
    name: "Abdominal Aorta (AAA Screening)",
    shortName: "AAA",
    category: "Vascular",
    indication: "AAA screening; flank/back pain in elderly; syncope with pain",
    views: ["Proximal aorta (subxiphoid transverse)", "Mid aorta (transverse)", "Distal aorta to bifurcation", "Longitudinal aorta"],
    keyFindings: ["Aortic diameter (AP + transverse)", "Intraluminal thrombus", "Periaortic hematoma", "ILiac vessels"],
    commonPitfalls: ["Measure outer wall to outer wall", "Bowel gas obscuring view — gentle pressure or patient repositioning", "Don't confuse IVC for aorta"],
    tip: "Aorta is pulsatile and LEFT of midline; IVC is compressible and RIGHT of midline.",
    icon: "🩸",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Max AP diameter (cm)", "Transverse diameter (cm)"],
    anomaliesDetected: ["Dilation >3cm (aneurysm threshold)", "Dilation >5.5cm (surgical threshold)", "Intraluminal thrombus", "Periaortic fluid"],
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    shortName: "Gallbladder",
    category: "Abdominal",
    indication: "RUQ pain; suspected cholecystitis; biliary colic; jaundice",
    views: ["Long-axis GB", "Short-axis GB", "CBD measurement", "Murphy's sign assessment"],
    keyFindings: ["Stones (hyperechoic + shadowing)", "Wall thickness (>3mm)", "Pericholecystic fluid", "CBD diameter", "Sonographic Murphy's sign"],
    commonPitfalls: ["Fasting state required ideally", "Contracted GB makes assessment difficult", "Polyps vs. stones (stones move with gravity)"],
    tip: "Stones move with patient position (roll patient). Wall-echo-shadow (WES) sign = packed stones.",
    icon: "🟡",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["GB wall thickness (mm)", "CBD diameter (mm)", "Stone size (mm)"],
    anomaliesDetected: ["Cholelithiasis", "Wall thickening >3mm", "Pericholecystic fluid", "CBD dilation >6mm", "Polyp"],
  },
  {
    id: "renal",
    name: "Renal (Hydronephrosis)",
    shortName: "Renal",
    category: "Abdominal",
    indication: "Flank pain; UTI; renal colic; acute kidney injury",
    views: ["Right kidney (longitudinal + transverse)", "Left kidney (longitudinal + transverse)", "Bladder (transverse + sagittal)"],
    keyFindings: ["Hydronephrosis grade", "Kidney size", "Cortical thickness", "Stones", "Perinephric fluid"],
    commonPitfalls: ["Renal sinus fat vs. hydronephrosis", "Full bladder causes false hydronephrosis — rescan post-void"],
    tip: "Grade: Mild = renal pelvis only; Moderate = calyces; Severe = cortical thinning.",
    icon: "🟤",
    difficulty: "Basic",
    estimatedTime: "4–6 min",
    aiMeasurements: ["Kidney length (cm)", "Cortical thickness (mm)", "Hydronephrosis grade"],
    anomaliesDetected: ["Hydronephrosis (mild/mod/severe)", "Renal stone", "Perinephric collection", "Cortical thinning"],
  },
  {
    id: "bladder-volume",
    name: "Bladder Volume",
    shortName: "Bladder Vol",
    category: "Abdominal",
    indication: "Urinary retention; post-void residual; catheter need assessment",
    views: ["Transverse bladder (max width + depth)", "Sagittal bladder (max length)"],
    keyFindings: ["3D dimensions for ellipsoid formula", "Wall abnormalities", "Intraluminal pathology"],
    commonPitfalls: ["Ovarian cysts can mimic bladder — trace the bladder wall continuously"],
    tip: "Volume = 0.523 × L × W × H (ellipsoid formula). >300mL suggests urinary retention.",
    icon: "🔵",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Bladder length (cm)", "Width (cm)", "Height (cm)", "Volume (mL)"],
    anomaliesDetected: ["Retention (>300mL)", "Debris/clot", "Mass", "Thickened wall"],
  },
  {
    id: "dvt",
    name: "DVT: Compression Ultrasound",
    shortName: "DVT",
    category: "Vascular",
    indication: "Suspected DVT; leg swelling; chest pain with leg symptoms (PE workup)",
    views: ["Common femoral vein (CFV)", "Femoral vein (mid-thigh)", "Popliteal vein", "Trifurcation"],
    keyFindings: ["Vein compressibility", "Intraluminal thrombus echogenicity", "Doppler flow pattern", "Augmentation"],
    commonPitfalls: ["Always compare to artery — arteries are pulsatile and don't fully compress", "Calf veins require experienced operators"],
    tip: "Normal: vein fully compresses (walls touch). DVT: vein non-compressible or partially compressible.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["CFV diameter (mm)", "Compressibility score"],
    anomaliesDetected: ["Non-compressible vein (DVT)", "Intraluminal echogenic material", "Absent augmentation"],
  },
  {
    id: "onsd",
    name: "Optic Nerve Sheath Diameter (ICP)",
    shortName: "ONSD",
    category: "Neuro",
    indication: "Suspected raised ICP; TBI; headache with neuro signs; pre-LP assessment",
    views: ["Transverse ONSD (3mm posterior to globe)", "Longitudinal ONSD"],
    keyFindings: ["ONSD measurement", "Globe architecture", "Posterior globe flattening (severe ICP)"],
    commonPitfalls: ["Measure exactly 3mm behind globe posterior wall", "Use light pressure only — globe is fragile"],
    tip: "ONSD >5.0–5.7mm (varies by study) correlates with ICP >20 mmHg. Use linear probe, standoff gel pad.",
    icon: "👁️",
    difficulty: "Basic",
    estimatedTime: "3–4 min",
    aiMeasurements: ["ONSD bilateral (mm)", "Globe axial length (mm)"],
    anomaliesDetected: ["Elevated ONSD (>5.7mm)", "Posterior globe flattening", "Papilledema signs"],
  },
  {
    id: "soft-tissue",
    name: "Soft Tissue / Abscess",
    shortName: "Soft Tissue",
    category: "Procedural",
    indication: "Skin and soft tissue infection; rule out abscess vs. cellulitis; foreign body",
    views: ["Affected region (transverse)", "Affected region (longitudinal)", "Surrounding tissue"],
    keyFindings: ["Fluid collection", "Internal echoes/debris", "Wall characteristics", "Vascularity (Doppler)", "Foreign body shadowing"],
    commonPitfalls: ["Cobblestone appearance = cellulitis (no drainable collection)", "Hypoechoic ≠ always abscess — compare to other side"],
    tip: "Squish sign: gentle compression causes swirling internal debris = abscess. Absence = solid mass or hematoma.",
    icon: "🔬",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Collection dimensions (cm)", "Depth from skin (cm)"],
    anomaliesDetected: ["Abscess (fluid + debris)", "Cellulitis (cobblestone)", "Foreign body", "Hematoma"],
  },
];

export const CATEGORIES: Category[] = [
  "Trauma",
  "Cardiac",
  "Lung",
  "OB",
  "Abdominal",
  "Vascular",
  "Neuro",
  "Procedural",
];

export const CATEGORY_COLORS: Record<Category, string> = {
  Trauma: "bg-red-500/20 text-red-300 border-red-500/30",
  Cardiac: "bg-rose-500/20 text-rose-300 border-rose-500/30",
  Lung: "bg-cyan-500/20 text-cyan-300 border-cyan-500/30",
  OB: "bg-purple-500/20 text-purple-300 border-purple-500/30",
  Abdominal: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  Vascular: "bg-blue-500/20 text-blue-300 border-blue-500/30",
  Neuro: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
  Procedural: "bg-slate-500/20 text-slate-300 border-slate-500/30",
};

export const CATEGORY_DOT: Record<Category, string> = {
  Trauma: "bg-red-400",
  Cardiac: "bg-rose-400",
  Lung: "bg-cyan-400",
  OB: "bg-purple-400",
  Abdominal: "bg-amber-400",
  Vascular: "bg-blue-400",
  Neuro: "bg-emerald-400",
  Procedural: "bg-slate-400",
};

export function getProtocolById(id: string): Protocol | undefined {
  return PROTOCOLS.find((p) => p.id === id);
}
