export type Category =
  | "Trauma"
  | "Cardiac"
  | "Lung"
  | "OB/GYN"
  | "Abdominal"
  | "Vascular"
  | "Neuro"
  | "Thyroid"
  | "MSK"
  | "Procedural";

export interface Protocol {
  id: string;
  name: string;
  shortName: string;
  category: Category;
  indication: string;
  views: string[];
  keyFindings: string[];
  commonPitfalls: string[];
  tip: string;
  icon: string;
  difficulty: "Basic" | "Intermediate" | "Advanced";
  estimatedTime: string;
  aiMeasurements: string[];
  anomaliesDetected: string[];
}

export const PROTOCOLS: Protocol[] = [
  // ── TRAUMA ──────────────────────────────────────────────────────────────────
  {
    id: "efast",
    name: "eFAST — Extended FAST",
    shortName: "eFAST",
    category: "Trauma",
    indication: "Blunt/penetrating trauma; hemodynamic instability; free fluid assessment",
    views: ["RUQ (Morison's Pouch)", "LUQ (Splenorenal)", "Pelvis (Retrovesical/Retrouterine)", "Subxiphoid Cardiac", "Bilateral Lung (×2)"],
    keyFindings: ["Free fluid (anechoic stripe)", "Pericardial effusion", "Lung sliding (PTX)", "Hemopneumothorax"],
    commonPitfalls: ["Perinephric fat vs. fluid", "Collapsed IVC vs. fluid", "Suboptimal subxiphoid window"],
    tip: "Always start with RUQ — highest yield in trauma. Compare both flanks symmetrically.",
    icon: "🔴",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Free fluid depth (mm)", "Pericardial effusion size"],
    anomaliesDetected: ["Free fluid", "Pericardial effusion", "Pneumothorax", "Hemothorax"],
  },

  // ── CARDIAC ─────────────────────────────────────────────────────────────────
  {
    id: "tte",
    name: "Transthoracic Echocardiogram (TTE)",
    shortName: "TTE",
    category: "Cardiac",
    indication: "Dyspnea; chest pain; heart failure evaluation; valve disease; pre-op cardiac assessment",
    views: [
      "Parasternal Long Axis (PLAX)",
      "Parasternal Short Axis — MV level",
      "Parasternal Short Axis — Papillary level",
      "Apical 4-Chamber (A4C)",
      "Apical 5-Chamber (A5C)",
      "Apical 2-Chamber (A2C)",
      "Apical Long Axis (A3C/APLAX)",
      "Subcostal 4-Chamber",
      "Subcostal IVC",
      "Suprasternal Notch (aortic arch)",
    ],
    keyFindings: ["LV systolic function (EF)", "Wall motion abnormality", "Pericardial effusion", "Valve pathology (regurgitation/stenosis)", "RV size and function", "LA/RA size"],
    commonPitfalls: ["Foreshortened apical views overestimate EF", "Epicardial fat mistaken for pericardial effusion", "Lateral wall dropout in A4C", "Subcostal window limited by bowel gas"],
    tip: "Start with PLAX to align cardiac axis, then rotate to PSAX. Left lateral decubitus position improves apical window dramatically.",
    icon: "❤️",
    difficulty: "Advanced",
    estimatedTime: "45–60 min",
    aiMeasurements: ["LV EF (%)", "EPSS (mm)", "IVSd (mm)", "LVPWd (mm)", "LVIDd (mm)", "LA diameter (cm)", "Aortic root (cm)", "E/A ratio"],
    anomaliesDetected: ["Reduced EF (<55%)", "Wall motion abnormality", "Pericardial effusion", "Aortic stenosis", "Mitral regurgitation", "LV hypertrophy", "RV dilation"],
  },
  {
    id: "cardiac-plax",
    name: "Cardiac: Parasternal Long Axis",
    shortName: "PLAX",
    category: "Cardiac",
    indication: "Cardiac function assessment; effusion; valve pathology",
    views: ["Parasternal Long Axis (PLAX)"],
    keyFindings: ["LV systolic function", "Pericardial effusion", "Aortic root dilation", "MV pathology", "EPSS"],
    commonPitfalls: ["Mistaking epicardial fat for effusion", "Off-axis view overestimates chamber size"],
    tip: "Probe at 3rd–4th ICS, left sternal border. Rotate counterclockwise to align with cardiac axis.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["EPSS (mm)", "LV internal dimension", "LA diameter", "Aortic root diameter"],
    anomaliesDetected: ["Pericardial effusion", "Reduced EF (EPSS >1cm)", "Aortic dilation", "Posterior effusion"],
  },
  {
    id: "cardiac-psax",
    name: "Cardiac: Parasternal Short Axis",
    shortName: "PSAX",
    category: "Cardiac",
    indication: "Wall motion assessment; RV pressure; LV geometry",
    views: ["PSAX — Mitral valve level", "PSAX — Papillary muscle level", "PSAX — Apical level"],
    keyFindings: ["Regional wall motion abnormality", "D-sign (RV strain)", "LV geometry (donut shape)"],
    commonPitfalls: ["True short axis requires circular LV — if elliptical, adjust rotation"],
    tip: "From PLAX, rotate probe 90° clockwise. Mitral valve level shows 'fish mouth' appearance.",
    icon: "❤️",
    difficulty: "Intermediate",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Fractional shortening", "D-sign severity"],
    anomaliesDetected: ["Wall motion abnormality", "RV strain (D-sign)", "Pericardial effusion"],
  },
  {
    id: "cardiac-a4c",
    name: "Cardiac: Apical 4-Chamber",
    shortName: "A4C",
    category: "Cardiac",
    indication: "EF estimation; chamber sizing; valve assessment",
    views: ["Apical 4-Chamber (A4C)"],
    keyFindings: ["All 4 chambers", "MV and TV function", "Apical wall motion", "EF (visual/biplane)"],
    commonPitfalls: ["Foreshortened apex gives falsely elevated EF", "Patient positioning critical (left lateral decubitus)"],
    tip: "Position patient in left lateral decubitus. Probe at cardiac apex, marker toward left shoulder.",
    icon: "❤️",
    difficulty: "Advanced",
    estimatedTime: "3–4 min",
    aiMeasurements: ["LV EF estimate (%)", "LA volume index", "E/A ratio estimate"],
    anomaliesDetected: ["Reduced EF", "RV dilation", "Apical wall motion abnormality", "Mitral regurgitation signs"],
  },
  {
    id: "ivc",
    name: "IVC Collapsibility (Fluid Status)",
    shortName: "IVC",
    category: "Cardiac",
    indication: "Volume status assessment; fluid responsiveness; CVP estimation",
    views: ["Subxiphoid IVC (longitudinal)", "M-mode through IVC at 2cm from junction"],
    keyFindings: ["IVC diameter (max)", "Collapsibility with respiration", "Respiratory variation"],
    commonPitfalls: ["IVC vs. aorta confusion", "Spontaneous breathing vs. ventilated patients — opposite interpretation"],
    tip: "Measure IVC 2cm from IVC-RA junction. Collapsibility >50% = likely volume responsive (spontaneous breathing).",
    icon: "❤️",
    difficulty: "Basic",
    estimatedTime: "2 min",
    aiMeasurements: ["IVC max diameter (cm)", "IVC min diameter (cm)", "Collapsibility Index (%)"],
    anomaliesDetected: ["Dilated IVC (>2.1cm)", "Plethoric IVC", "Flat IVC (<0.9cm)"],
  },

  // ── LUNG ─────────────────────────────────────────────────────────────────────
  {
    id: "lung-blue",
    name: "Lung: BLUE Protocol",
    shortName: "BLUE Protocol",
    category: "Lung",
    indication: "Dyspnea; respiratory failure; pneumonia vs. CHF vs. PE vs. PTX differentiation",
    views: ["Upper BLUE Point (bilateral)", "Lower BLUE Point (bilateral)", "PLAPS Point (bilateral)"],
    keyFindings: ["A-lines (air, normal/PTX)", "B-lines (fluid, interstitial)", "Lung sliding", "Pleural effusion", "Lung consolidation"],
    commonPitfalls: ["3+ B-lines per zone required to be significant", "Z-lines vs. B-lines (Z-lines don't reach far field)"],
    tip: "Use high-frequency linear probe for pleural line detail. Low-frequency for deeper pathology.",
    icon: "🫁",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["B-line count per zone", "Pleural effusion depth (mm)"],
    anomaliesDetected: ["B-lines (≥3/zone)", "Absent lung sliding", "Consolidation", "Pleural effusion"],
  },
  {
    id: "lung-effusion",
    name: "Lung: Pleural Effusion",
    shortName: "Pleural Effusion",
    category: "Lung",
    indication: "Pleural effusion detection and quantification; thoracentesis guidance",
    views: ["Posterior-lateral chest (sitting or lateral decubitus)", "Diaphragm visualization"],
    keyFindings: ["Anechoic vs. complex effusion", "Diaphragm descent", "Compressive atelectasis", "Fibrinous septations"],
    commonPitfalls: ["Confusing ascites with pleural effusion — find diaphragm landmark"],
    tip: "Spine sign: if vertebrae visible below diaphragm on left side, effusion present.",
    icon: "🫁",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Effusion depth (cm)", "Estimated volume (mL)"],
    anomaliesDetected: ["Simple effusion", "Complex/exudative effusion", "Septated effusion"],
  },

  // ── OB/GYN ───────────────────────────────────────────────────────────────────
  {
    id: "ob-first-trimester",
    name: "OB: First Trimester Dating",
    shortName: "OB 1st Tri",
    category: "OB/GYN",
    indication: "Gestational age confirmation; viable IUP; ectopic exclusion",
    views: ["Longitudinal uterus (GS)", "Embryo with CRL measurement", "Adnexa bilateral", "Cervix"],
    keyFindings: ["Gestational sac", "Yolk sac", "Embryo (CRL)", "Fetal cardiac motion", "Adnexal masses"],
    commonPitfalls: ["Pseudogestational sac (ectopic) vs. true GS — look for double decidual sign", "Empty sac — may be too early (<5.5 weeks)"],
    tip: "Transabdominal first, then transvaginal if unclear. CRL: straight line crown to rump, neutral position.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "5–10 min",
    aiMeasurements: ["CRL (mm)", "Gestational Age (weeks+days)", "EDD", "GS mean diameter (mm)"],
    anomaliesDetected: ["Subchorionic hematoma", "Irregular GS", "No cardiac motion (>6 weeks CRL)", "Adnexal mass", "Free fluid (ectopic risk)"],
  },
  {
    id: "ob-second-trimester",
    name: "OB: Second Trimester Biometry",
    shortName: "OB 2nd Tri",
    category: "OB/GYN",
    indication: "Gestational age; fetal growth; EFW; anatomy survey",
    views: ["BPD/HC plane (transthalamic)", "AC plane (stomach/UV junction)", "Femur length", "Placental location"],
    keyFindings: ["Fetal biometry parameters", "EFW percentile", "AFI/deepest pocket", "Placental position"],
    commonPitfalls: ["BPD: must visualize cavum septi pellucidi and thalami", "AC: true transverse at liver/umbilical vein junction"],
    tip: "Standard growth curves: Hadlock 1984 for EFW; Hadlock 1982 for individual parameters.",
    icon: "👶",
    difficulty: "Intermediate",
    estimatedTime: "10–15 min",
    aiMeasurements: ["BPD (mm)", "HC (mm)", "AC (mm)", "FL (mm)", "EFW (g)", "GA by biometry", "EFW percentile"],
    anomaliesDetected: ["IUGR pattern (AC lag)", "Macrosomia", "FL/AC discordance", "Placenta previa signs"],
  },
  {
    id: "pelvic-female",
    name: "Pelvic Ultrasound (Female)",
    shortName: "Pelvic US",
    category: "OB/GYN",
    indication: "Pelvic pain; abnormal uterine bleeding; ovarian cyst evaluation; infertility workup",
    views: [
      "Uterus — sagittal (length & AP)",
      "Uterus — transverse (width)",
      "Endometrium measurement",
      "Right ovary (longitudinal + transverse)",
      "Left ovary (longitudinal + transverse)",
      "Cul-de-sac (free fluid)",
      "Transvaginal survey (if indicated)",
    ],
    keyFindings: ["Uterine size and morphology", "Endometrial thickness", "Ovarian size and follicles", "Free fluid in cul-de-sac", "Adnexal masses"],
    commonPitfalls: ["Full bladder required for TA; empty bladder for TV", "Fibroids can distort uterine measurements", "Ovaries may be hidden behind bowel gas"],
    tip: "For postmenopausal bleeding: endometrial thickness >4–5mm warrants biopsy. Use TV for superior resolution of endometrium.",
    icon: "🔵",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Uterus length (cm)", "Uterus width (cm)", "Uterus AP (cm)", "Endometrial thickness (mm)", "Right ovary volume (cc)", "Left ovary volume (cc)"],
    anomaliesDetected: ["Endometrial thickening (>5mm postmenopausal)", "Ovarian cyst (simple/complex)", "Fibroid", "Free fluid", "Adnexal mass"],
  },
  {
    id: "scrotal",
    name: "Male Pelvis: Scrotal & Prostate",
    shortName: "Scrotal US",
    category: "OB/GYN",
    indication: "Scrotal pain; testicular mass; infertility evaluation; prostate assessment",
    views: [
      "Right testis — longitudinal",
      "Right testis — transverse (superior, mid, inferior)",
      "Left testis — longitudinal",
      "Left testis — transverse",
      "Bilateral epididymis (head, body, tail)",
      "Color/power Doppler — bilateral testes",
      "Transabdominal prostate (transverse + sagittal)",
    ],
    keyFindings: ["Testicular echogenicity and size", "Epididymis echogenicity", "Vascularity by Doppler", "Prostate size and echogenicity", "Intratesticular lesion"],
    commonPitfalls: ["Absent testicular flow on Doppler: torsion until proven otherwise — urgent urology referral", "Doppler settings must be optimized for low-flow states", "Compare both sides simultaneously with split-screen"],
    tip: "Split-screen color Doppler comparison is essential for torsion evaluation — side-by-side is the standard.",
    icon: "🔵",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Testis length, width, height (mm)", "Testicular volume (mL)", "Prostate volume (mL)", "Epididymal head diameter (mm)"],
    anomaliesDetected: ["Absent flow (torsion)", "Heterogeneous echotexture", "Intratesticular mass", "Epididymo-orchitis", "Hydrocele", "Varicocele", "Prostate enlargement"],
  },

  // ── ABDOMINAL ────────────────────────────────────────────────────────────────
  {
    id: "ruq",
    name: "Right Upper Quadrant (RUQ) Ultrasound",
    shortName: "RUQ US",
    category: "Abdominal",
    indication: "RUQ pain; abnormal LFTs; jaundice; gallstones; hepatomegaly evaluation",
    views: [
      "Liver — longitudinal (right lobe)",
      "Liver — transverse (portal vein + hepatic veins)",
      "Gallbladder — long axis",
      "Gallbladder — short axis",
      "CBD measurement at porta hepatis",
      "Murphy's sign assessment",
      "Right kidney — longitudinal (comparison)",
    ],
    keyFindings: ["Gallstones (hyperechoic + posterior shadowing)", "GB wall thickness", "CBD diameter", "Liver echogenicity and size", "Sonographic Murphy's sign", "Pericholecystic fluid"],
    commonPitfalls: ["Fasting ≥4h required — contracted GB obscures stones", "WES (wall-echo-shadow) sign = packed stones; can be mistaken for gas", "CBD measured inner wall to inner wall at porta hepatis"],
    tip: "Start in right intercostal oblique, sweep through GB. Roll patient left to confirm stone mobility. CBD >6mm (or >7mm post-cholecystectomy) is abnormal.",
    icon: "🟡",
    difficulty: "Basic",
    estimatedTime: "30–45 min",
    aiMeasurements: ["GB wall thickness (mm)", "CBD diameter (mm)", "Stone size (mm)", "Liver span (cm)"],
    anomaliesDetected: ["Cholelithiasis", "Acute cholecystitis (wall >3mm + Murphy's + stones)", "CBD dilation (>6mm)", "Hepatomegaly", "Hepatic steatosis", "Pericholecystic fluid"],
  },
  {
    id: "gallbladder",
    name: "Gallbladder",
    shortName: "Gallbladder",
    category: "Abdominal",
    indication: "RUQ pain; suspected cholecystitis; biliary colic; jaundice",
    views: ["Long-axis GB", "Short-axis GB", "CBD measurement", "Murphy's sign assessment"],
    keyFindings: ["Stones (hyperechoic + shadowing)", "Wall thickness (>3mm)", "Pericholecystic fluid", "CBD diameter", "Sonographic Murphy's sign"],
    commonPitfalls: ["Fasting state required ideally", "Contracted GB makes assessment difficult", "Polyps vs. stones (stones move with gravity)"],
    tip: "Stones move with patient position (roll patient). Wall-echo-shadow (WES) sign = packed stones.",
    icon: "🟡",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["GB wall thickness (mm)", "CBD diameter (mm)", "Stone size (mm)"],
    anomaliesDetected: ["Cholelithiasis", "Wall thickening >3mm", "Pericholecystic fluid", "CBD dilation >6mm", "Polyp"],
  },
  {
    id: "renal",
    name: "Renal (Hydronephrosis)",
    shortName: "Renal",
    category: "Abdominal",
    indication: "Flank pain; UTI; renal colic; acute kidney injury",
    views: ["Right kidney (longitudinal + transverse)", "Left kidney (longitudinal + transverse)", "Bladder (transverse + sagittal)"],
    keyFindings: ["Hydronephrosis grade", "Kidney size", "Cortical thickness", "Stones", "Perinephric fluid"],
    commonPitfalls: ["Renal sinus fat vs. hydronephrosis", "Full bladder causes false hydronephrosis — rescan post-void"],
    tip: "Grade: Mild = renal pelvis only; Moderate = calyces; Severe = cortical thinning.",
    icon: "🟤",
    difficulty: "Basic",
    estimatedTime: "4–6 min",
    aiMeasurements: ["Kidney length (cm)", "Cortical thickness (mm)", "Hydronephrosis grade"],
    anomaliesDetected: ["Hydronephrosis (mild/mod/severe)", "Renal stone", "Perinephric collection", "Cortical thinning"],
  },
  {
    id: "bladder-volume",
    name: "Bladder Volume",
    shortName: "Bladder Vol",
    category: "Abdominal",
    indication: "Urinary retention; post-void residual; catheter need assessment",
    views: ["Transverse bladder (max width + depth)", "Sagittal bladder (max length)"],
    keyFindings: ["3D dimensions for ellipsoid formula", "Wall abnormalities", "Intraluminal pathology"],
    commonPitfalls: ["Ovarian cysts can mimic bladder — trace the bladder wall continuously"],
    tip: "Volume = 0.523 × L × W × H. >300mL suggests urinary retention.",
    icon: "🔵",
    difficulty: "Basic",
    estimatedTime: "2–3 min",
    aiMeasurements: ["Bladder length (cm)", "Width (cm)", "Height (cm)", "Volume (mL)"],
    anomaliesDetected: ["Retention (>300mL)", "Debris/clot", "Mass", "Thickened wall"],
  },

  // ── VASCULAR ─────────────────────────────────────────────────────────────────
  {
    id: "carotid-duplex",
    name: "Carotid Duplex Ultrasound",
    shortName: "Carotid Duplex",
    category: "Vascular",
    indication: "TIA/stroke workup; carotid bruit; pre-operative assessment; stenosis surveillance",
    views: [
      "CCA — transverse sweep (proximal to bifurcation)",
      "CCA — sagittal + Doppler (proximal, mid, distal)",
      "Bifurcation — grayscale + Doppler",
      "ICA — sagittal + Doppler (proximal, mid, distal)",
      "ECA — sagittal + Doppler",
      "Vertebral artery — sagittal + Doppler (bilateral)",
      "Repeat contralateral side",
    ],
    keyFindings: ["Intimal-medial thickness (IMT)", "Plaque (location, echogenicity, surface)", "PSV/EDV at CCA, ICA, ECA", "ICA/CCA PSV ratio", "Vertebral flow direction"],
    commonPitfalls: ["Doppler angle must not exceed 60° — perpendicular angles are contraindicated", "Distinguish physiologic bifurcation turbulence from pathologic stenosis", "Retrograde vertebral flow = subclavian steal syndrome"],
    tip: "Temporal artery tap test: brief tapping on the superficial temporal artery creates a 'bouncing' waveform in the ECA — confirms ICA vs. ECA identity.",
    icon: "🩸",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["IMT (mm)", "CCA PSV (cm/s)", "ICA PSV (cm/s)", "ICA/CCA ratio", "ECA PSV (cm/s)", "Vertebral PSV (cm/s)"],
    anomaliesDetected: ["ICA stenosis (>50%, >70%)", "Plaque with surface ulceration", "Near-occlusion", "Occlusion", "Retrograde vertebral flow", "IMT >1.0mm"],
  },
  {
    id: "le-venous-duplex",
    name: "Lower Extremity Venous Duplex (DVT)",
    shortName: "LE Venous Duplex",
    category: "Vascular",
    indication: "Leg swelling/pain; elevated D-dimer; cancer surveillance; DVT risk",
    views: [
      "Common femoral vein (CFV) — compression + Doppler",
      "Femoral vein — mid/distal thigh compression",
      "Popliteal vein — compression + Doppler",
      "Trifurcation (peroneal, posterior tibial, anterior tibial)",
      "GSV at saphenofemoral junction",
      "Augmentation maneuvers (calf squeeze)",
    ],
    keyFindings: ["Vein compressibility", "Intraluminal echogenic material", "Augmentation response", "Spontaneous flow pattern", "Phasicity with respiration"],
    commonPitfalls: ["Duplicate femoral veins — interrogate both", "Calf DVT limited sensitivity without Doppler augmentation", "Chronic DVT: thickened, echogenic wall ≠ acute thrombus"],
    tip: "Normal vein fully compresses (walls touch). Non-compressibility = DVT. Compare Doppler phasicity: loss = proximal obstruction.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["CFV diameter (mm)", "Popliteal vein diameter (mm)", "Compressibility score", "Flow velocity (cm/s)"],
    anomaliesDetected: ["Acute DVT (non-compressible)", "Chronic DVT (wall thickening)", "Partial thrombosis", "Absent augmentation (proximal obstruction)"],
  },
  {
    id: "dvt",
    name: "DVT: Compression Ultrasound (POCUS)",
    shortName: "DVT POCUS",
    category: "Vascular",
    indication: "Suspected DVT at bedside; leg swelling; PE workup",
    views: ["Common femoral vein (CFV)", "Femoral vein (mid-thigh)", "Popliteal vein", "Trifurcation"],
    keyFindings: ["Vein compressibility", "Intraluminal thrombus echogenicity", "Doppler flow pattern", "Augmentation"],
    commonPitfalls: ["Always compare to artery — arteries are pulsatile and don't fully compress", "Calf veins require experienced operators"],
    tip: "Normal: vein fully compresses (walls touch). DVT: vein non-compressible or partially compressible.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "5–8 min",
    aiMeasurements: ["CFV diameter (mm)", "Compressibility score"],
    anomaliesDetected: ["Non-compressible vein (DVT)", "Intraluminal echogenic material", "Absent augmentation"],
  },
  {
    id: "ue-arterial-duplex",
    name: "Upper Extremity Arterial Duplex",
    shortName: "UE Arterial",
    category: "Vascular",
    indication: "Arm claudication; digital ischemia; post-catheterization; dialysis access planning; thoracic outlet syndrome",
    views: [
      "Subclavian artery — Doppler",
      "Axillary artery — Doppler",
      "Brachial artery — Doppler",
      "Radial artery — Doppler",
      "Ulnar artery — Doppler",
      "Palmar arch patency",
    ],
    keyFindings: ["Waveform character (triphasic/biphasic/monophasic)", "PSV and waveform at each segment", "Pressure gradients", "Plaque or stenosis", "Thrombosis"],
    commonPitfalls: ["Systolic pressure differential >15mmHg between arms = significant asymmetry", "Triphasic → monophasic waveform transition = significant inflow disease", "Thoracic outlet requires dynamic (postural) assessment"],
    tip: "Compare bilateral brachial pressures. A >20% PSV elevation at a focal segment indicates hemodynamically significant stenosis.",
    icon: "🩸",
    difficulty: "Intermediate",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Brachial PSV (cm/s)", "Radial PSV (cm/s)", "Ulnar PSV (cm/s)", "Pressure index"],
    anomaliesDetected: ["Stenosis (focal PSV elevation)", "Occlusion (absent flow)", "Monophasic waveform (inflow disease)", "Pseudoaneurysm", "AV fistula"],
  },
  {
    id: "ue-venous-duplex",
    name: "Upper Extremity Venous Duplex (DVT)",
    shortName: "UE Venous",
    category: "Vascular",
    indication: "Arm/hand swelling; PICC/catheter-related thrombosis; effort thrombosis (Paget-Schroetter); cancer surveillance",
    views: [
      "Internal jugular vein — compression + Doppler",
      "Subclavian vein — Doppler",
      "Axillary vein — compression + Doppler",
      "Brachial veins — compression",
      "Cephalic and basilic veins",
    ],
    keyFindings: ["Vein compressibility", "Intraluminal thrombus", "Doppler phasicity", "Augmentation with arm compression", "PICC/catheter position"],
    commonPitfalls: ["Subclavian vein not compressible due to clavicle — rely on Doppler only", "IJV thrombosis may be incidental finding", "Respiratory phasicity loss indicates central (SVC) obstruction"],
    tip: "Respiratory variation in the subclavian/axillary Doppler signal indicates patency to central veins. Loss of variation = central obstruction.",
    icon: "🩺",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["IJV diameter (mm)", "Subclavian vein flow (cm/s)", "Compressibility score"],
    anomaliesDetected: ["Acute DVT (non-compressible)", "PICC-associated thrombosis", "Effort thrombosis (subclavian)", "SVC syndrome signs"],
  },
  {
    id: "renal-artery-duplex",
    name: "Renal Artery Duplex Ultrasound",
    shortName: "Renal Artery",
    category: "Vascular",
    indication: "Resistant hypertension; renovascular disease; renal artery stenosis screening; transplant surveillance",
    views: [
      "Aorta at renal artery origins — transverse",
      "Right renal artery — origin + mid segment Doppler",
      "Left renal artery — origin + mid segment Doppler",
      "Right renal parenchyma — segmental/interlobar arteries",
      "Left renal parenchyma — segmental/interlobar arteries",
      "Kidney lengths — bilateral",
    ],
    keyFindings: ["Renal artery PSV at origin", "Renal/aortic ratio (RAR)", "Resistive index (RI) parenchymal", "Kidney size asymmetry", "Post-stenotic turbulence"],
    commonPitfalls: ["Bowel gas is the major limiting factor — patient prep essential", "Accessory renal arteries in 20–30% of patients", "RAR >3.5 indicates significant stenosis", "Long exam — patient positioning is crucial"],
    tip: "PSV >180 cm/s at renal artery origin + RAR >3.5 = significant stenosis. RI >0.8 = poor response to revascularization.",
    icon: "🩸",
    difficulty: "Advanced",
    estimatedTime: "45–75 min",
    aiMeasurements: ["Renal artery PSV (cm/s)", "Aortic PSV (cm/s)", "RAR (renal/aortic ratio)", "RI (resistive index)", "Kidney length (cm)"],
    anomaliesDetected: ["Renal artery stenosis (RAR >3.5)", "Fibromuscular dysplasia", "Kidney size asymmetry (>2cm)", "Elevated RI (parenchymal disease)"],
  },
  {
    id: "abi",
    name: "ABI & Physiologic Segmental Pressures",
    shortName: "ABI",
    category: "Vascular",
    indication: "Peripheral arterial disease assessment; claudication; non-healing wounds; ischemia risk stratification",
    views: [
      "Bilateral brachial pressures (baseline)",
      "High thigh cuff pressure",
      "Above-knee (AK) cuff pressure",
      "Below-knee (BK) cuff pressure",
      "Ankle pressures (DP + PT bilateral)",
      "Toe pressures (TBI) if indicated",
    ],
    keyFindings: ["ABI calculation (ankle ÷ brachial)", "Segmental pressure gradients", "Waveform character at each level", "TBI for calcified vessels"],
    commonPitfalls: ["Calcified vessels (diabetics, ESRD): ABI >1.4 is non-compressible — use TBI instead", "ABI 0.91–1.0 = borderline; 0.71–0.90 = mild PAD; 0.41–0.70 = moderate; ≤0.40 = severe", "Exercise ABI adds sensitivity when resting ABI is normal"],
    tip: "Always take the higher of DP and PT for the ankle pressure. ABI ≤0.9 is diagnostic of PAD. ABI >1.4 = incompressible — order TBI.",
    icon: "📊",
    difficulty: "Basic",
    estimatedTime: "30–45 min",
    aiMeasurements: ["Right ABI", "Left ABI", "Segmental pressures (mmHg)", "TBI"],
    anomaliesDetected: ["ABI ≤0.9 (PAD)", "ABI >1.4 (calcified, non-compressible)", "Segmental gradient >20mmHg", "Critical limb ischemia (ABI <0.4)"],
  },
  {
    id: "aaa",
    name: "Abdominal Aorta (AAA Screening)",
    shortName: "AAA",
    category: "Vascular",
    indication: "AAA screening; flank/back pain in elderly; syncope with pain",
    views: ["Proximal aorta (subxiphoid transverse)", "Mid aorta (transverse)", "Distal aorta to bifurcation", "Longitudinal aorta"],
    keyFindings: ["Aortic diameter (AP + transverse)", "Intraluminal thrombus", "Periaortic hematoma", "Iliac vessels"],
    commonPitfalls: ["Measure outer wall to outer wall", "Bowel gas obscuring view — gentle pressure or reposition", "Don't confuse IVC for aorta"],
    tip: "Aorta is pulsatile and LEFT of midline; IVC is compressible and RIGHT of midline.",
    icon: "🩸",
    difficulty: "Basic",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Max AP diameter (cm)", "Transverse diameter (cm)"],
    anomaliesDetected: ["Dilation >3cm (aneurysm threshold)", "Dilation >5.5cm (surgical threshold)", "Intraluminal thrombus", "Periaortic fluid"],
  },
  {
    id: "vein-mapping",
    name: "Vein Mapping (Pre-Access / CABG)",
    shortName: "Vein Mapping",
    category: "Vascular",
    indication: "Pre-operative saphenous vein conduit planning for CABG; dialysis access planning; PICC line mapping",
    views: [
      "GSV at SFJ — diameter + compressibility",
      "GSV thigh segment — diameter every 10cm",
      "GSV knee — diameter",
      "GSV lower leg — diameter",
      "Small saphenous vein (SSV)",
      "Cephalic vein — UE (diameter every 10cm)",
      "Basilic vein — UE (diameter every 10cm)",
    ],
    keyFindings: ["Vein diameter at each segment", "Compressibility (no DVT)", "Vein depth from skin", "Continuity (no segments)", "Varicosities"],
    commonPitfalls: ["Tourniquet application improves vein distension for mapping", "Measure in standing position for lower extremity — supine underestimates diameter", "Deep veins must be assessed for DVT before harvest"],
    tip: "Vein diameter ≥3mm is considered adequate for CABG conduit. Diameter ≥2.5mm at wrist is adequate for dialysis fistula creation.",
    icon: "🗺️",
    difficulty: "Intermediate",
    estimatedTime: "30–60 min",
    aiMeasurements: ["GSV diameter per segment (mm)", "Cephalic vein diameter (mm)", "Basilic vein diameter (mm)", "Depth from skin (cm)"],
    anomaliesDetected: ["Inadequate diameter (<3mm)", "Thrombosed segment", "Varicose segment", "Deep accessory system dependence"],
  },
  {
    id: "avf-surveillance",
    name: "AV Fistula / Graft Surveillance",
    shortName: "AVF Surveillance",
    category: "Vascular",
    indication: "Dialysis access monitoring; maturation assessment; dysfunction evaluation (poor flow, clotting, difficult cannulation)",
    views: [
      "Arterial anastomosis — Doppler",
      "Venous outflow — Doppler sweep",
      "Mid-access — Doppler",
      "Juxta-anastomotic vein segment",
      "Outflow vein to central veins",
      "Brachial artery inflow — Doppler + volume flow",
    ],
    keyFindings: ["Brachial artery volume flow (mL/min)", "PSV at anastomosis and outflow", "Stenosis PSV ratio", "Access vein diameter and depth", "Thrombus"],
    commonPitfalls: ["Volume flow <500 mL/min predicts access failure", "PSV ratio >2:1 at stenosis = hemodynamically significant", "Aneurysms common — measure largest diameter", "Central stenosis presents as diffuse arm swelling + high pressures"],
    tip: "Volume flow calculation: π × r² × TAMEAN × 60. A flow >600 mL/min indicates maturation. Surveillance every 3–6 months reduces thrombosis risk.",
    icon: "🔄",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Brachial artery volume flow (mL/min)", "Access vein diameter (mm)", "Stenosis PSV ratio", "Anastomosis PSV (cm/s)"],
    anomaliesDetected: ["Stenosis (PSV ratio >2:1)", "Thrombosis", "Pseudoaneurysm", "Low flow (<500 mL/min)", "Steal syndrome signs"],
  },
  {
    id: "venous-reflux",
    name: "Lower Extremity Venous Reflux Study",
    shortName: "Venous Reflux",
    category: "Vascular",
    indication: "Varicose veins; chronic venous insufficiency; post-thrombotic syndrome; pre-ablation mapping",
    views: [
      "SFJ — reflux with Valsalva/cuff release",
      "GSV thigh — reflux assessment",
      "GSV below knee — reflux",
      "SSV at SPJ — reflux with calf compression",
      "Deep system — CFV, FV, popliteal vein reflux",
      "Perforating veins — bidirectional flow",
    ],
    keyFindings: ["Reflux duration at SFJ and GSV (>0.5s = pathologic)", "Perforating vein reflux (>0.35s bidirectional flow)", "GSV diameter in standing position", "SPJ competence", "Deep vein reflux"],
    commonPitfalls: ["Study must be performed in standing or reverse Trendelenburg position — supine gives false negatives", "Reflux >0.5s in superficial veins is pathologic; >1s in deep veins is pathologic", "Augmentation should be distal-to-proximal (cuff inflation then release)"],
    tip: "Perform in standing position. Augment distally and release to provoke reflux. Mark GSV with skin marker for ablation planning.",
    icon: "🔁",
    difficulty: "Intermediate",
    estimatedTime: "45–60 min (bilateral)",
    aiMeasurements: ["Reflux duration (seconds)", "GSV diameter standing (mm)", "Perforator diameter (mm)"],
    anomaliesDetected: ["GSV reflux (>0.5s)", "SSV reflux", "Perforator incompetence", "SFJ incompetence", "Post-thrombotic changes"],
  },

  // ── THYROID ──────────────────────────────────────────────────────────────────
  {
    id: "thyroid",
    name: "Thyroid Ultrasound",
    shortName: "Thyroid US",
    category: "Thyroid",
    indication: "Palpable thyroid nodule; elevated TSH/T4; goiter evaluation; nodule surveillance; pre-biopsy planning",
    views: [
      "Right lobe — transverse sweep (superior to inferior)",
      "Right lobe — longitudinal (length measurement)",
      "Isthmus — transverse (AP diameter)",
      "Left lobe — transverse sweep",
      "Left lobe — longitudinal",
      "Nodule(s) — 3 planes with measurements",
      "Vascularity — color/power Doppler",
      "Lymph nodes — bilateral central and lateral",
    ],
    keyFindings: ["Lobe dimensions and volume", "Isthmus thickness", "Nodule size, echogenicity, composition", "Nodule margins and orientation", "Echogenic foci (microcalcifications, comet-tail)", "Lymph node morphology"],
    commonPitfalls: ["TI-RADS scoring requires correct classification of composition (cystic >50% drops score)", "Comet-tail artifacts = benign colloid; microcalcifications = high-risk feature", "Posterior shadowing from calcification obscures deeper nodule assessment"],
    tip: "Use ACR TI-RADS: score each nodule for composition, echogenicity, shape, margin, echogenic foci. TR1/TR2 = no FNA; TR3 ≥1.5cm; TR4 ≥1.0cm; TR5 ≥0.5cm.",
    icon: "🫁",
    difficulty: "Basic",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Right lobe volume (mL)", "Left lobe volume (mL)", "Isthmus AP (mm)", "Nodule dimensions (mm)", "ACR TI-RADS score"],
    anomaliesDetected: ["Thyroid nodule (solid/cystic/mixed)", "Microcalcifications (high suspicion)", "Irregular margins", "Taller-than-wide shape", "Goiter", "Lymphadenopathy", "Hashimoto pattern"],
  },

  // ── NEURO ────────────────────────────────────────────────────────────────────
  {
    id: "onsd",
    name: "Optic Nerve Sheath Diameter (ICP)",
    shortName: "ONSD",
    category: "Neuro",
    indication: "Suspected raised ICP; TBI; headache with neuro signs; pre-LP assessment",
    views: ["Transverse ONSD (3mm posterior to globe)", "Longitudinal ONSD"],
    keyFindings: ["ONSD measurement", "Globe architecture", "Posterior globe flattening (severe ICP)"],
    commonPitfalls: ["Measure exactly 3mm behind globe posterior wall", "Use light pressure only — globe is fragile"],
    tip: "ONSD >5.0–5.7mm (varies by study) correlates with ICP >20 mmHg. Use linear probe with standoff gel pad.",
    icon: "👁️",
    difficulty: "Basic",
    estimatedTime: "3–4 min",
    aiMeasurements: ["ONSD bilateral (mm)", "Globe axial length (mm)"],
    anomaliesDetected: ["Elevated ONSD (>5.7mm)", "Posterior globe flattening", "Papilledema signs"],
  },
  {
    id: "tcd",
    name: "Transcranial Doppler (TCD)",
    shortName: "TCD",
    category: "Neuro",
    indication: "Stroke risk in sickle cell disease; cerebral vasospasm (post-SAH); intracranial stenosis; right-to-left shunt detection; brain death confirmation",
    views: [
      "Transtemporal window — MCA (45–65mm)",
      "Transtemporal window — ACA (60–80mm)",
      "Transtemporal window — PCA (60–70mm)",
      "Transorbital window — ophthalmic artery (REDUCE POWER)",
      "Suboccipital window — basilar artery (80–120mm)",
      "Suboccipital window — vertebral arteries (40–70mm)",
    ],
    keyFindings: ["MCA PSV (normal: 50–120 cm/s)", "Lindegaard Ratio (vasospasm)", "Vertebral/basilar flow direction", "Microembolic signals (HITS)", "Ophthalmic artery flow direction"],
    commonPitfalls: ["Temporal window absent in 10–20% of patients (elderly women, thick skull)", "REDUCE power to minimum MI for transorbital window — retinal risk", "MCA flows TOWARD probe (positive); ACA flows AWAY (negative)"],
    tip: "Vasospasm: MCA PSV >120 cm/s + Lindegaard Ratio >3. For PFO detection, inject agitated saline during Valsalva and count HITS within 25 cardiac cycles.",
    icon: "🧠",
    difficulty: "Advanced",
    estimatedTime: "45–60 min",
    aiMeasurements: ["MCA PSV (cm/s)", "ACA PSV (cm/s)", "PCA PSV (cm/s)", "Basilar PSV (cm/s)", "Lindegaard Ratio"],
    anomaliesDetected: ["MCA PSV >120 cm/s (vasospasm/sickle cell risk)", "Reversed ophthalmic flow (ICA occlusion)", "Absent flow (brain death criteria)", "HITS (microemboli)", "Lindegaard Ratio >3"],
  },

  // ── MSK ──────────────────────────────────────────────────────────────────────
  {
    id: "shoulder",
    name: "Shoulder Ultrasound (Rotator Cuff)",
    shortName: "Shoulder US",
    category: "MSK",
    indication: "Rotator cuff tear; impingement syndrome; shoulder pain; biceps tendon pathology; AC joint assessment",
    views: [
      "Biceps tendon — transverse (long axis groove)",
      "Biceps tendon — longitudinal",
      "Subscapularis tendon — transverse + longitudinal",
      "Supraspinatus tendon — long axis (modified Crass)",
      "Supraspinatus tendon — short axis",
      "Infraspinatus tendon — long + short axis",
      "AC joint — transverse",
      "Subacromial-subdeltoid bursa",
      "Dynamic impingement (arm elevation)",
    ],
    keyFindings: ["Supraspinatus continuity and echogenicity", "Bursal and articular surface tears", "Tendon thickness", "Biceps tendon integrity and position", "Subdeltoid bursal fluid", "Calcific deposits"],
    commonPitfalls: ["Anisotropy artifact mimics tears — always scan perpendicular to tendon fibers", "Tendon thickness must be compared to contralateral side", "Full-thickness tears: absent tendon, 'naked tuberosity' sign", "Patient must be in standard position (modified Crass for supraspinatus)"],
    tip: "Modified Crass position: arm internally rotated, hand on ipsilateral back pocket. This stretches supraspinatus for best visualization. Dynamic assessment during arm elevation can provoke impingement.",
    icon: "🦴",
    difficulty: "Intermediate",
    estimatedTime: "20–30 min",
    aiMeasurements: ["Supraspinatus thickness (mm)", "Bursal fluid depth (mm)", "Tear size if present (mm)", "Biceps tendon diameter (mm)"],
    anomaliesDetected: ["Full-thickness rotator cuff tear", "Partial-thickness tear (bursal/articular)", "Tendinosis", "Calcific tendinopathy", "Biceps tendon rupture/dislocation", "Subdeltoid bursitis"],
  },

  // ── PROCEDURAL ───────────────────────────────────────────────────────────────
  {
    id: "soft-tissue",
    name: "Soft Tissue / Abscess",
    shortName: "Soft Tissue",
    category: "Procedural",
    indication: "Skin and soft tissue infection; rule out abscess vs. cellulitis; foreign body",
    views: ["Affected region (transverse)", "Affected region (longitudinal)", "Surrounding tissue"],
    keyFindings: ["Fluid collection", "Internal echoes/debris", "Wall characteristics", "Vascularity (Doppler)", "Foreign body shadowing"],
    commonPitfalls: ["Cobblestone appearance = cellulitis (no drainable collection)", "Hypoechoic ≠ always abscess — compare to other side"],
    tip: "Squish sign: gentle compression causes swirling internal debris = abscess. Absence = solid mass or hematoma.",
    icon: "🔬",
    difficulty: "Intermediate",
    estimatedTime: "3–5 min",
    aiMeasurements: ["Collection dimensions (cm)", "Depth from skin (cm)"],
    anomaliesDetected: ["Abscess (fluid + debris)", "Cellulitis (cobblestone)", "Foreign body", "Hematoma"],
  },
];

export const CATEGORIES: Category[] = [
  "Trauma",
  "Cardiac",
  "Lung",
  "OB/GYN",
  "Abdominal",
  "Vascular",
  "Neuro",
  "Thyroid",
  "MSK",
  "Procedural",
];

export const CATEGORY_PILL: Record<Category, { bg: string; text: string; dot: string }> = {
  Trauma:     { bg: "#fee2e2", text: "#dc2626", dot: "#ef4444" },
  Cardiac:    { bg: "#fce7f3", text: "#db2777", dot: "#ec4899" },
  Lung:       { bg: "#e0f2fe", text: "#0284c7", dot: "#38bdf8" },
  "OB/GYN":  { bg: "#f3e8ff", text: "#9333ea", dot: "#a855f7" },
  Abdominal:  { bg: "#fef9c3", text: "#a16207", dot: "#fbbf24" },
  Vascular:   { bg: "#dbeafe", text: "#2563eb", dot: "#60a5fa" },
  Neuro:      { bg: "#d1fae5", text: "#059669", dot: "#34d399" },
  Thyroid:    { bg: "#ccfbf1", text: "#0d9488", dot: "#2dd4bf" },
  MSK:        { bg: "#fef3c7", text: "#d97706", dot: "#f59e0b" },
  Procedural: { bg: "#f1f5f9", text: "#64748b", dot: "#94a3b8" },
};

// Kept for backwards-compat in any component still referencing these
export const CATEGORY_COLORS = CATEGORY_PILL;
export const CATEGORY_DOT: Record<Category, string> = Object.fromEntries(
  Object.entries(CATEGORY_PILL).map(([k, v]) => [k, v.dot])
) as Record<Category, string>;

export function getProtocolById(id: string): Protocol | undefined {
  return PROTOCOLS.find((p) => p.id === id);
}
